FROM ubuntu:22.04
RUN apt-get update && apt-get install -y gcc gcc-multilib make socat && rm -rf /var/lib/apt/lists/*
RUN useradd -m ctf
WORKDIR /home/ctf
COPY fmt.c .
RUN gcc -o fmt fmt.c -fno-stack-protector -z execstack -no-pie -fno-pie
RUN chown -R root:ctf /home/ctf && chmod 750 /home/ctf/fmt && chmod 440 /home/ctf/fmt.c
EXPOSE 1338
CMD ["socat", "TCP-LISTEN:1338,reuseaddr,fork", "EXEC:/home/ctf/fmt,stderr"]
